### ISSUE TITLE
some problems to solve

### ISSUE THREAD

**Issue by ColdPiLLoW710** [alvarobasilys/RoadDamageRecognition#1]
Greeting from the internet！I have some problems in operating the app：When I upload the video and put the “run” button the app shut down itself. Perhaps something wrong with it. Look foward to your earliest reply. thx！

**Comment by alvarobasilys** [comment]
Can you check again? the issue is before clicking the run button, you need to initialize the ROI by clicking ROI Spin Box.
I add some lines so when the video loads, ROI will automatically draw.

**Comment by alvarobasilys** [comment]
closed
